import { describe, expect, it } from 'vitest';
import { merchantProjection } from '@argus-challenge/testkit';
import type { AttestationInput } from '../attestations/attestation-bindings.js';
import { profileFromProjection, requirePhoneProfile } from './profile.js';

const attestation: AttestationInput = {
  envelope: 'envelope',
  signature: 'signature',
  publicKey: 'public-key',
  keyId: 'device-key',
};

function phoneProjection(cryptoDeviceId: string) {
  return merchantProjection({
    identification: {
      crypto_device_id: cryptoDeviceId,
      crypto_verified: true,
      browserDetails: {
        browserName: 'Mobile Safari',
        browserVersion: '26',
        device: 'mobile',
        os: 'iOS',
        userAgent: 'Mozilla/5.0 (iPhone) Mobile',
      },
    },
  });
}

describe('SSO projection profile', () => {
  it('records a verified projection bound to the SSO attestation key', () => {
    expect(
      profileFromProjection('argus-session', attestation, phoneProjection('43a46f1d08'))
    ).toMatchObject({
      isPhone: true,
      projectionDeviceBound: true,
    });
  });

  it('rejects a phone projection generated by a different device key', () => {
    const profile = profileFromProjection(
      'argus-session',
      attestation,
      phoneProjection('8193b45484')
    );

    expect(requirePhoneProfile(profile, 'start', 'https://merchant.example/failure')).toEqual({
      ok: false,
      status: 403,
      body: {
        error: 'sso_projection_device_unbound',
        leg: 'start',
        message: 'The Argus scan does not match the device completing this SSO leg.',
        failureReturnUrl: 'https://merchant.example/failure',
      },
    });
  });
});
